/** @type {import('@stryker-mutator/api/core').PartialStrykerOptions} */
export default {
  mutate: [
    "apps/api/src/admin-meta-gateway.ts",
    "apps/api/src/admin-meta-protocol.ts",
    "apps/api/src/admin-meta-routes.ts",
    "apps/api/src/meta-graph-gateway.ts",
    "apps/api/src/meta-webhook-protocol.ts",
    "apps/api/src/meta-webhook-routes.ts",
    "apps/api/src/meta-webhook-rpc.ts",
    "apps/worker/src/meta-inbound-processor.ts",
    "apps/worker/src/meta-inbound-rpc.ts",
    "apps/worker/src/whatsapp-ai-processor.ts:56-75",
    "apps/worker/src/whatsapp-ai-processor.ts:135-162",
    "apps/worker/src/whatsapp-ai-processor.ts:216-217",
    "apps/worker/src/whatsapp-ai-processor.ts:252-253",
    "apps/worker/src/whatsapp-ai-processor.ts:360-390",
    "apps/worker/src/whatsapp-ai-processor.ts:465-477",
    "apps/worker/src/whatsapp-ai-rpc.ts:404-469",
    "apps/worker/src/whatsapp-ai-rpc.ts:563-573",
    "apps/worker/src/whatsapp-ai-rpc.ts:613-613",
    "apps/worker/src/whatsapp-ai-rpc.ts:641-665",
    "apps/worker/src/whatsapp-ai-rpc.ts:736-769",
    "packages/ai/src/**/*.ts",
    "!packages/ai/src/index.ts",
    "packages/database/src/type-normalizer.ts",
  ],
  ignorePatterns: [
    ".npm/**",
    ".stryker-tmp/**",
    "coverage/**",
    "reports/**",
    "docs/**",
    "supabase/**",
  ],
  disableTypeChecks: "{apps/api/src,apps/worker/src,packages/ai/src,packages/database/src}/**/*.ts",
  testRunner: "vitest",
  vitest: {
    configFile: "vitest.config.ts",
    related: false,
  },
  reporters: ["clear-text", "progress", "json"],
  jsonReporter: {
    fileName: "reports/mutation/mutation.json",
  },
  thresholds: {
    high: 90,
    low: 90,
    break: 90,
  },
  concurrency: 2,
};
